name: Tests
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pytest:
    name: pytest
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        python-version: [3.6, 3.7]
        tf-version: [2.0, 2.1, 2.2, 2.3]
        poetry-version: [1.0.0]

    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - uses: Gr1N/setup-poetry@v2
      with:
        poetry-version: ${{ matrix.poetry-version }}
    - run: poetry run python -m pip install --upgrade pip
    - run: poetry add tensorflow@~${TF_VERSION}
      env:
        TF_VERSION: ${{ matrix.tf-version }}
    - run: poetry install
    - run: poetry run bash scripts/test.sh